### ISSUE TITLE
Support for Postgres

### ISSUE THREAD

**Issue by josylad** [terminalkitten/django-insights#2]
Hello, 
I want to ask if this package works with Apps with a Postgres DB because the Readme keeps mentioning SQLite. 
@terminalkitten

**Comment by terminalkitten** [comment]
@josylad Hi! I've not tested it with a Postgresql database. But it's still Django ORM, so it should work.

**Comment by josylad** [comment]
> @josylad Hi! I've not tested it with a Postgresql database. But it's still Django ORM, so it should work.

Hello, 
I did test it and it works. 

Another question I have is about putting the page behind authentication to prevent unauthorised access. Is that possible? 
@terminalkitten

**Comment by terminalkitten** [comment]
@josylad  Nice!

> Another question I have is about putting the page behind authentication to prevent unauthorised access. Is that possible?

On the `main`  branch there is a solution but I've had no time to test this solution. It basically adds custom permissions on the AdminView by adding them with a setting `INSIGHT_DASHBOARD_PERMISSIONS`

```python
# Extra permission classes
INSIGHT_DASHBOARD_PERMISSIONS = (
    StaffMemberAndSuperUserRequired,
)
```

As a alternative this might work, you could use `InsightsDashboardView` as generic view:

```python
from django_insights.views import InsightsDashboardView

class MyDashboardView(ViewPermission, InsightsDashboardView):
 ...
```

You probably also need to adjust the router.
